#Example configuration
#Core configuration
[core]
tick_rate = 240
use_icons = false
directory_first = true

sort_by_name = "asc"
sort_by_date = "none"
sort_by_attr = "none"
  
[color_scheme]
foreground = "White"
background = "Reset"
normal_black = "Black"
normal_red = "Red"
normal_green = "Green"
normal_yellow = "Yellow"
normal_blue = "Blue"
normal_magneta = "Magneta"
normal_cyan = "Cyan"
normal_white = "White"
light_black = "Gray"
light_red = "LightRed"
light_green = "LightGreen"
light_yellow = "LightYellow"
light_blue = "LightBlue"
light_magneta = "LightMagenta"
light_cyan = "LightCyan"
light_white = "White"

normal_dir_background = "Black"
cursor_dir_background = "LightBlue"
select_dir_background = "Green"
normal_dir_foreground = "White"
cursor_dir_foreground = "Yellow"
select_dir_foreground = "Black"

normal_file_background = "Black"
cursor_file_background = "LightBlue"
select_file_background = "Green"
normal_file_foreground = "LightGreen"
cursor_file_foreground = "Yellow"
select_file_foreground = "Black"

normal_link_background = "Black"
cursor_link_background = "LightBlue"
select_link_background = "Green"
normal_link_foreground = "LightYellow"
cursor_link_foreground = "Yellow"
select_link_foreground = "Black"

[colors_files]
# extension = "Color"
# Example: html = "Green"
rs = "Red"
toml = "Red"
default = "White"

[keyboard_cfg]
# keybindings
# function = keybinding
# keybinding:
# key - one per line
# possible keys - chars + digits
# modifier - one per line
# possible modifiers - C (Control), A (Alt), S (Shift)

# Examples:
# quit = { key = "q", modifier = "C" }
quit = { key = "q", modifier = "C" }

focus_left_panel = { key = "1", modifier = "C" }
focus_right_panel = { key = "2", modifier = "C" }

move_down = { key = "j" }
move_up = { key = "k" }

close = { key = "q" }

open = { key = "l" }
open_as_tab = { key = "L" }

navigate_up = { key = "h" }

delete = { key = "d" }

move_fs_item = { key = "c" }

rename = { key = "r" }
create = { key = "n" }
accept = { key = "enter" }

copy_fs_item = { key = "y" }

search_in_panel = { key = "/" }

select_prev = { key = "X", modifier = "S" }
select_next = { key = "x" }

change_focus_panels = { key = "tab" }

# go to home
command_1 = { key = "H", modifier = "S" }
# go to projects
command_2 = { key = "P", modifier = "S" }

sort_by_name_asc = { key = "f1"}
sort_by_name_desc = { key = "f1", modifier = "C" }
sort_by_date_asc = { key = "f2"}
sort_by_date_desc = { key = "f2", modifier = "C" }
sort_by_attr_asc = { key = "f3"}
sort_by_attr_desc = { key = "f3", modifier = "C" }

filesystem_item_props = { key = "i" }

[file_associated_programs]
default = "open"
png = "open"
md = "hx"
rs = "hx"
php = "hx"
go = "hx"
c = "hx"
cpp = "hx"

[hotkey_commands_programs]
command_1 = "/Users/shapkin"
command_2 = "/Users/shapkin/projects"
command_3 = "/Users/shapkin"
command_4 = "/Users/shapkin"
command_5 = "/Users/shapkin"
command_6 = "/Users/shapkin"
command_7 = "/Users/shapkin"
command_8 = "/Users/shapkin"
command_9 = "/Users/shapkin"
