#Example configuration
#Core configuration
[core]
tick_rate = 240
use_icons = true

[color_scheme]
foregorund = "White"
background = "Reset"
normal_black = "Black"
normal_red = "Red"
normal_green = "Green"
normal_yellow = "Yellow"
normal_blue = "Blue"
normal_magneta = "Magneta"
normal_cyan = "Cyan"
normal_white = "White"
light_black = "Gray"
light_red = "LightRed"
light_green = "LightGreen"
light_yellow = "LightYellow"
light_blue = "LightBlue"
light_magneta = "LightMagenta"
light_cyan = "LightCyan"
light_white = "White"

[keyboard_cfg]
# quit = { key = "q", modifier = "C" }
quit = { key = "q" }

# focus_left_panel = { key = "h" }
focus_left_panel = { key = "1", modifier = "C" }

# focus_right_panel = { key = "l" }
focus_right_panel = { key = "2", modifier = "C" }

move_down = { key = "j" }
move_up = { key = "k" }

# next_tab = { key = "T" }
# prev_tab = { key = "T" }

close = { key = "q" }
open = { key = "l" }
open_as_tab = { key = "L" }
# navigate_up = { key = "backspace" }
navigate_up = { key = "h" }
delete = { key = "d" }
# move_left = { key = "h", modifier = "C" }
# move_right = { key = "l", modifier = "C" }
move_fs_item = { key = "c" }
rename = { key = "r" }
create = { key = "n" }
accept = { key = "enter" }
# copy_to_left = { key = "z", modifier = "C" }
# copy_to_right = { key = "x", modifier = "C" }
copy_fs_item = { key = "y" }
# search_in_panel = { key = "s", modifier = "C" }
search_in_panel = { key = "/" }
select_prev = { key = "X", modifier = "S" }
select_next = { key = "x" }

change_focus_panels = { key = "tab" }

# go to home
command_1 = { key = "H", modifier = "S" }
# go to projects
command_2 = { key = "P", modifier = "S" }

# [icons_dir]
# ".git" = ""
# node_modules = ""
# default = ""

# [icons_files]
# ".gitignore" = ""
# ".gitmodules" = ""
# rs = ""
# cs = ""
# cpp = "ﭱ"
# c = ""
# hpp = ""
# h = ""
# js = ""
# ts = ""
# jsx = ""
# tsx = "ﰆ"
# html = ""
# css = ""
# sass = ""
# toml = ""
# yaml = ""
# php = ""
# py = ""
# rb = ""
# java = ""
# lock = ""
# default = ""

[file_associated_programs]
default = "open"
png = "open"
md = "hx"
rs = "hx"
php = "hx"
go = "hx"
c = "hx"
cpp = "hx"

[hotkey_commands_programs]
command_1 = "/Users/shapkin"
command_2 = "/Users/shapkin/projects"
command_3 = "/Users/shapkin"
command_4 = "/Users/shapkin"
command_5 = "/Users/shapkin"
command_6 = "/Users/shapkin"
command_7 = "/Users/shapkin"
command_8 = "/Users/shapkin"
command_9 = "/Users/shapkin"
